### ISSUE TITLE
ttshitu_config设置问题

### ISSUE THREAD

**Issue by t66y1** [0honus0/CaoLiu_AutoReply#46]
你好！

请问如果验证码使用ttshitu_config，需要怎么设置config.yml和AutoReply.py？是直接把账号输入到userid？密码输入到apikey？需不需要把config.yml和AutoReply.py里的内容修改为username、password？

config.yml:
```
    # 配置为 ttshitu_config 时,从 http://www.ttshitu.com 处获取账号密码
    ttshitu_config:
        userid: "xxx"
        apikey: "xxxxx"
```

AutoReply.py
```
config.get("gobal_config").get("ttshitu_config") is not None:
    userid : str = config.get("gobal_config").get("ttshitu_config").get("userid")
    apikey : str = config.get("gobal_config").get("ttshitu_config").get("apikey")
    captcha_function = "ttshitu"
```
